# Generated by Django 3.2.16 on 2022-12-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('cik', models.CharField(blank=True, max_length=20)),
                ('sector', models.CharField(blank=True, max_length=20)),
                ('industry_category', models.CharField(blank=True, max_length=20)),
                ('company_url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
