# Generated by Django 3.2.16 on 2022-12-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221209_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
