# Generated by Django 3.2.16 on 2022-12-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('indicator_name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
    ]
