# Generated by Django 3.2.16 on 2022-12-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_financial_indicator_financialindicator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialIndicator',
            new_name='Indicator',
        ),
    ]
