# Generated by Django 3.2.16 on 2022-12-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_name',
            field=models.CharField(max_length=150),
        ),
    ]
