# Generated by Django 3.2.16 on 2022-12-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_statement_statement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.BigIntegerField(unique=True)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_period', models.CharField(max_length=50)),
                ('filling_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('url', models.CharField(max_length=150)),
                ('urlfinal', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=10)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
