# Generated by Django 3.2.16 on 2022-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_statementmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementmetadata',
            name='statement_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='statementmetadata',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='statementmetadata',
            name='urlfinal',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
