# Generated by Django 3.2.16 on 2022-12-18 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221218_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementmetadata',
            name='statement_type',
        ),
        migrations.AddField(
            model_name='statementmetadata',
            name='id_statement_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.statement'),
        ),
    ]
