# Generated by Django 3.2.16 on 2022-12-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221218_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementmetadata',
            name='unique_hash',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
