# Generated by Django 3.2.16 on 2022-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_statementmetadata_unique_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementmetadata',
            name='filling_date',
            field=models.DateTimeField(),
        ),
    ]
