# Generated by Django 3.2.16 on 2022-12-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_statementmetadata_filling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementmetadata',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statementmetadata',
            name='filling_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='statementmetadata',
            name='unique_hash',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
