# Generated by Django 3.2.16 on 2022-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221218_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementmetadata',
            name='end_date',
            field=models.DateField(),
        ),
    ]
