# Generated by Django 3.2.16 on 2022-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_statementmetadata_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cik',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
