# Generated by Django 3.2.16 on 2022-12-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_statementmetadata_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('id_Financial_Indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicator')),
                ('id_financial_statement_meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statementmetadata')),
            ],
        ),
    ]
