# Generated by Django 3.2.16 on 2022-12-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_financialsvalues_financialsvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialsValue',
            new_name='FinancialValue',
        ),
    ]
